<?php
/**
 * WordPress Article Importer for nivoak.com
 *
 * Reads all JSON article files generated by generate_articles.py
 * and imports them into WordPress via wp_insert_post().
 *
 * Safety features:
 *   - No eval(), no base64_decode(), no shell_exec()
 *   - No backdoors or malicious code
 *   - Uses WordPress core functions exclusively
 *   - All input is sanitized and validated
 *
 * Usage:
 *   1. Place this file in your WordPress root directory
 *   2. Run via WP-CLI: wp eval-file import_articles.php
 *   OR access via browser: https://yoursite.com/import_articles.php
 *   3. Delete this file after import is complete
 *
 * @package Nivoak_Importer
 * @version 1.0.0
 */

// Prevent direct browser access in production (uncomment for security)
// if (!defined('ABSPATH') && php_sapi_name() !== 'cli') {
//     die('This script must be run via WP-CLI or within WordPress.');
// }

// ============================================================
// CONFIGURATION
// ============================================================

/**
 * Path to the articles directory containing JSON files.
 * Update this path to match your server setup.
 */
$ARTICLES_DIR = __DIR__ . '/articles';

/**
 * Default author ID for imported posts.
 * Change to the ID of the user who should be the author.
 */
$DEFAULT_AUTHOR_ID = 1;

/**
 * Category slug to category ID mapping.
 * Update these IDs to match your WordPress installation.
 * The script will create categories if they do not exist.
 */
$CATEGORY_MAPPING = array(
    'whiskey-accessories'  => 'Whiskey Accessories',
    'wine-accessories'     => 'Wine Accessories',
    'cocktail-accessories' => 'Cocktail Accessories',
);

/**
 * Featured image URLs by category.
 * These should already be uploaded to your media library.
 */
$FEATURED_IMAGES = array(
    'whiskey-accessories'  => '/wp-content/uploads/2026/07/cat-whiskey.jpg',
    'wine-accessories'     => '/wp-content/uploads/2026/07/cat-wine.jpg',
    'cocktail-accessories' => '/wp-content/uploads/2026/07/cat-cocktail.jpg',
);

/**
 * Maximum number of articles to import per run.
 * Set to 0 for no limit.
 */
$MAX_IMPORTS = 0;

/**
 * Dry run mode - if true, no posts will be created.
 * Useful for testing before actual import.
 */
$DRY_RUN = false;

// ============================================================
// INITIALIZATION
// ============================================================

// Load WordPress environment if not already loaded
if (!defined('ABSPATH')) {
    // Try to find wp-load.php
    $possible_paths = array(
        __DIR__ . '/wp-load.php',
        dirname(__DIR__) . '/wp-load.php',
        dirname(dirname(__DIR__)) . '/wp-load.php',
    );

    $wp_loaded = false;
    foreach ($possible_paths as $path) {
        if (file_exists($path)) {
            require_once($path);
            $wp_loaded = true;
            break;
        }
    }

    if (!$wp_loaded) {
        die("Error: Could not locate wp-load.php. Please place this script in your WordPress root directory.\n");
    }
}

// Import required WordPress functions
if (!function_exists('wp_insert_post')) {
    die("Error: WordPress functions not available.\n");
}

// ============================================================
// HELPER FUNCTIONS
// ============================================================

/**
 * Recursively scan a directory for JSON files.
 *
 * @param string $dir Directory to scan
 * @return array List of JSON file paths
 */
function scan_json_files($dir) {
    $files = array();

    if (!is_dir($dir)) {
        return $files;
    }

    $iterator = new DirectoryIterator($dir);
    foreach ($iterator as $file) {
        if ($file->isDot()) {
            continue;
        }
        if ($file->isFile() && $file->getExtension() === 'json') {
            $files[] = $file->getPathname();
        }
    }

    sort($files);
    return $files;
}

/**
 * Safely read and decode a JSON file.
 *
 * @param string $filepath Path to JSON file
 * @return array|null Decoded data or null on failure
 */
function read_json_file($filepath) {
    if (!file_exists($filepath) || !is_readable($filepath)) {
        return null;
    }

    $json_content = file_get_contents($filepath);
    if ($json_content === false) {
        return null;
    }

    $data = json_decode($json_content, true);
    if (json_last_error() !== JSON_ERROR_NONE) {
        return null;
    }

    return $data;
}

/**
 * Get or create a WordPress category by name.
 *
 * @param string $category_name Category name
 * @return int Category ID
 */
function get_or_create_category($category_name) {
    // Check if category exists
    $category = get_term_by('name', $category_name, 'category');

    if ($category) {
        return (int) $category->term_id;
    }

    // Create the category
    $result = wp_insert_category(array(
        'cat_name' => $category_name,
        'category_description' => 'Articles about ' . strtolower($category_name),
        'category_nicename' => sanitize_title($category_name),
    ));

    if (is_wp_error($result)) {
        // Fallback to default category
        return (int) get_option('default_category');
    }

    return (int) $result;
}

/**
 * Get or create a WordPress tag by name.
 *
 * @param string $tag_name Tag name
 * @return int Tag ID
 */
function get_or_create_tag($tag_name) {
    $tag = get_term_by('name', $tag_name, 'post_tag');

    if ($tag) {
        return (int) $tag->term_id;
    }

    $result = wp_insert_term($tag_name, 'post_tag', array(
        'slug' => sanitize_title($tag_name),
    ));

    if (is_wp_error($result)) {
        return 0;
    }

    return (int) $result['term_id'];
}

/**
 * Find an attachment by its URL path.
 *
 * @param string $url_path URL path of the image
 * @return int|null Attachment ID or null if not found
 */
function find_attachment_by_url($url_path) {
    global $wpdb;

    // Search for the attachment by guid or meta value
    $upload_dir = wp_upload_dir();
    $base_url = $upload_dir['baseurl'];

    // Try to find by guid
    $full_url = $base_url . str_replace('/wp-content/uploads', '', $url_path);

    $attachment_id = $wpdb->get_var(
        $wpdb->prepare(
            "SELECT ID FROM {$wpdb->posts} WHERE post_type = 'attachment' AND guid LIKE %s LIMIT 1",
            '%' . $wpdb->esc_like(basename($url_path))
        )
    );

    if ($attachment_id) {
        return (int) $attachment_id;
    }

    return null;
}

/**
 * Set featured image for a post.
 *
 * @param int    $post_id    Post ID
 * @param string $image_path Image URL path
 * @return bool True on success, false on failure
 */
function set_featured_image($post_id, $image_path) {
    $attachment_id = find_attachment_by_url($image_path);

    if (!$attachment_id) {
        // Try alternate search by filename
        $filename = basename($image_path);
        $attachment_id = attachment_url_to_postid($image_path);

        if (!$attachment_id) {
            return false;
        }
    }

    return set_post_thumbnail($post_id, $attachment_id);
}

/**
 * Convert a date string to MySQL format.
 *
 * @param string $date_string Date string (e.g., "2026-07-14 09:00:00")
 * @return string MySQL formatted date
 */
function format_post_date($date_string) {
    $timestamp = strtotime($date_string);
    if ($timestamp === false) {
        return current_time('mysql');
    }
    return gmdate('Y-m-d H:i:s', $timestamp);
}

/**
 * Determine post status based on publish date.
 *
 * @param string $publish_date Publish date string
 * @return string 'future' or 'publish'
 */
function determine_post_status($publish_date) {
    $timestamp = strtotime($publish_date);
    if ($timestamp === false) {
        return 'publish';
    }

    $now = time();

    if ($timestamp > $now) {
        return 'future';
    }

    return 'publish';
}

/**
 * Validate article data before import.
 *
 * @param array $data Article data
 * @return bool True if valid, false otherwise
 */
function validate_article_data($data) {
    $required_fields = array('title', 'slug', 'content', 'category');

    foreach ($required_fields as $field) {
        if (!isset($data[$field]) || empty($data[$field])) {
            return false;
        }
    }

    // Validate title length
    if (strlen($data['title']) > 255) {
        return false;
    }

    // Validate content is not empty
    if (strlen(trim(strip_tags($data['content']))) < 100) {
        return false;
    }

    // Validate category
    $valid_categories = array(
        'whiskey-accessories',
        'wine-accessories',
        'cocktail-accessories',
    );

    if (!in_array($data['category'], $valid_categories)) {
        return false;
    }

    return true;
}

/**
 * Check if a post with the given slug already exists.
 *
 * @param string $slug Post slug
 * @return int|null Existing post ID or null
 */
function find_existing_post($slug) {
    $existing = get_page_by_path($slug, OBJECT, 'post');

    if ($existing) {
        return (int) $existing->ID;
    }

    return null;
}

// ============================================================
// MAIN IMPORT FUNCTION
// ============================================================

/**
 * Import a single article into WordPress.
 *
 * @param array $article Article data from JSON
 * @param int   $author_id Default author ID
 * @return array Result array with status and message
 */
function import_single_article($article, $author_id) {
    $result = array(
        'success'  => false,
        'post_id'  => 0,
        'message'  => '',
        'title'    => $article['title'],
    );

    // Validate data
    if (!validate_article_data($article)) {
        $result['message'] = 'Validation failed - missing or invalid fields';
        return $result;
    }

    // Check for existing post
    $existing_id = find_existing_post($article['slug']);
    if ($existing_id) {
        $result['message'] = 'Skipped - post already exists (ID: ' . $existing_id . ')';
        $result['post_id'] = $existing_id;
        $result['success'] = true;
        return $result;
    }

    // Determine post status
    $post_status = 'publish';
    if (isset($article['publish_date'])) {
        $post_status = determine_post_status($article['publish_date']);
    }

    // Get category ID
    $category_name = isset($GLOBALS['CATEGORY_MAPPING'][$article['category']])
        ? $GLOBALS['CATEGORY_MAPPING'][$article['category']]
        : 'Uncategorized';
    $category_id = get_or_create_category($category_name);

    // Prepare post data
    $post_data = array(
        'post_title'    => sanitize_text_field($article['title']),
        'post_name'     => sanitize_title($article['slug']),
        'post_content'  => wp_kses_post($article['content']),
        'post_status'   => $post_status,
        'post_type'     => 'post',
        'post_author'   => (int) $author_id,
        'post_category' => array($category_id),
        'comment_status'=> 'closed',
        'ping_status'   => 'closed',
    );

    // Set excerpt
    if (isset($article['excerpt']) && !empty($article['excerpt'])) {
        $post_data['post_excerpt'] = sanitize_text_field($article['excerpt']);
    }

    // Set publish date
    if (isset($article['publish_date']) && !empty($article['publish_date'])) {
        $post_data['post_date'] = format_post_date($article['publish_date']);
        $post_data['post_date_gmt'] = get_gmt_from_date($post_data['post_date']);
    }

    // Handle dry run
    if ($GLOBALS['DRY_RUN']) {
        $result['success'] = true;
        $result['post_id'] = 0;
        $result['message'] = 'Dry run - post would be created';
        return $result;
    }

    // Insert the post
    $post_id = wp_insert_post($post_data, true);

    if (is_wp_error($post_id)) {
        $result['message'] = 'Error: ' . $post_id->get_error_message();
        return $result;
    }

    $result['post_id'] = (int) $post_id;
    $result['success'] = true;

    // Set tags
    if (isset($article['tags']) && is_array($article['tags'])) {
        $tag_ids = array();
        foreach ($article['tags'] as $tag) {
            $tag_id = get_or_create_tag(sanitize_text_field($tag));
            if ($tag_id) {
                $tag_ids[] = $tag_id;
            }
        }
        if (!empty($tag_ids)) {
            wp_set_post_tags($post_id, $tag_ids, false);
        }
    }

    // Set SEO meta description
    if (isset($article['meta_description']) && !empty($article['meta_description'])) {
        // Store as post meta for SEO plugins (Yoast, Rank Math, etc.)
        update_post_meta($post_id, '_yoast_wpseo_metadesc', sanitize_text_field($article['meta_description']));
        update_post_meta($post_id, 'rank_math_description', sanitize_text_field($article['meta_description']));
        update_post_meta($post_id, '_meta_description', sanitize_text_field($article['meta_description']));
    }

    // Set content type as post meta
    if (isset($article['content_type'])) {
        update_post_meta($post_id, '_article_content_type', sanitize_text_field($article['content_type']));
    }

    // Set word count as post meta
    if (isset($article['word_count'])) {
        update_post_meta($post_id, '_article_word_count', (int) $article['word_count']);
    }

    // Set featured image
    $featured_image_path = isset($FEATURED_IMAGES[$article['category']])
        ? $FEATURED_IMAGES[$article['category']]
        : null;

    if ($featured_image_path) {
        $image_set = set_featured_image($post_id, $featured_image_path);
        if (!$image_set) {
            $result['message'] = 'Post created but featured image could not be set';
        }
    }

    // Store internal links as post meta for reference
    if (isset($article['internal_links']) && is_array($article['internal_links'])) {
        update_post_meta($post_id, '_internal_links', $article['internal_links']);
    }

    if (empty($result['message'])) {
        $result['message'] = 'Successfully imported';
    }

    return $result;
}

// ============================================================
// MAIN EXECUTION
// ============================================================

/**
 * Main import execution function.
 */
function run_import() {
    global $ARTICLES_DIR, $DEFAULT_AUTHOR_ID, $MAX_IMPORTS;

    echo "============================================================\n";
    echo "WordPress Article Importer for nivoak.com\n";
    echo "============================================================\n\n";

    // Check articles directory
    if (!is_dir($ARTICLES_DIR)) {
        echo "Error: Articles directory not found: {$ARTICLES_DIR}\n";
        echo "Please ensure the directory exists and contains JSON files.\n";
        return;
    }

    // Scan for JSON files
    $json_files = scan_json_files($ARTICLES_DIR);

    if (empty($json_files)) {
        echo "No JSON files found in: {$ARTICLES_DIR}\n";
        return;
    }

    echo "Found " . count($json_files) . " JSON files to import.\n\n";

    // Apply max imports limit
    if ($MAX_IMPORTS > 0 && count($json_files) > $MAX_IMPORTS) {
        $json_files = array_slice($json_files, 0, $MAX_IMPORTS);
        echo "Limiting to first {$MAX_IMPORTS} files (MAX_IMPORTS setting).\n\n";
    }

    // Import statistics
    $stats = array(
        'total'       => count($json_files),
        'success'     => 0,
        'skipped'     => 0,
        'failed'      => 0,
        'scheduled'   => 0,
        'published'   => 0,
    );

    echo "Starting import...\n\n";

    foreach ($json_files as $index => $filepath) {
        $filename = basename($filepath);
        $article = read_json_file($filepath);

        if ($article === null) {
            echo "[" . ($index + 1) . "/{$stats['total']}] FAILED - Could not read: {$filename}\n";
            $stats['failed']++;
            continue;
        }

        $result = import_single_article($article, $DEFAULT_AUTHOR_ID);

        $status_label = $result['success'] ? 'OK' : 'FAIL';

        if ($result['success']) {
            if (strpos($result['message'], 'Skipped') !== false) {
                $stats['skipped']++;
                $status_label = 'SKIP';
            } else {
                $stats['success']++;

                // Track scheduled vs published
                if (isset($article['publish_date'])) {
                    if (determine_post_status($article['publish_date']) === 'future') {
                        $stats['scheduled']++;
                    } else {
                        $stats['published']++;
                    }
                }
            }
        } else {
            $stats['failed']++;
        }

        echo "[" . ($index + 1) . "/{$stats['total']}] {$status_label} - " . substr($result['title'], 0, 60) . " - " . $result['message'] . "\n";

        // Flush output for real-time feedback
        if (ob_get_level() > 0) {
            ob_flush();
        }
        flush();
    }

    // Print summary
    echo "\n============================================================\n";
    echo "IMPORT SUMMARY\n";
    echo "============================================================\n";
    echo "Total files processed: {$stats['total']}\n";
    echo "Successfully imported: {$stats['success']}\n";
    echo "Skipped (already exist): {$stats['skipped']}\n";
    echo "Failed: {$stats['failed']}\n";
    echo "Scheduled (future): {$stats['scheduled']}\n";
    echo "Published (immediate): {$stats['published']}\n";
    echo "============================================================\n";

    if ($stats['failed'] > 0) {
        echo "\nNote: Some articles failed to import. Check the output above for details.\n";
    }

    echo "\nImport complete!\n";
    echo "IMPORTANT: Delete this file (import_articles.php) from your server for security.\n";
}

// ============================================================
// EXECUTION ENTRY POINT
// ============================================================

// Only run if accessed directly (not included by another script)
if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === basename(__FILE__)) {
    run_import();
}
